# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .types import BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePostRole

__all__ = ["BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePostRole"]
