# This file was auto-generated by Fern from our API Definition.

import typing

BodyCreateServiceAccountApiKeyV1ServiceAccountsServiceAccountUserIdApiKeysPostPermissionsOne = typing.Union[
    typing.Literal["all"], typing.Any
]
