# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel


class AgentDeploymentPercentageStrategy(UncheckedBaseModel):
    type: typing.Optional[typing.Literal["percentage"]] = None
    traffic_percentage: float = pydantic.Field()
    """
    Traffic percentage to deploy
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
