# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .agent_analysis_items_input_data_collection_item import AgentAnalysisItemsInputDataCollectionItem
from .agent_analysis_items_input_evaluation_criteria_item import AgentAnalysisItemsInputEvaluationCriteriaItem


class AgentAnalysisItemsInput(UncheckedBaseModel):
    evaluation_criteria: typing.Optional[typing.List[AgentAnalysisItemsInputEvaluationCriteriaItem]] = None
    data_collection: typing.Optional[typing.List[AgentAnalysisItemsInputDataCollectionItem]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
