# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel


class AlertingWebhookSecretHeaderValue(UncheckedBaseModel):
    """
    A custom webhook header value, encrypted at rest.
    """

    encrypted_value: str
    nonce: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
