# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .constant_schema_override_constant_value import ConstantSchemaOverrideConstantValue


class ApiIntegrationWebhookOverridesSchemaOverridesValue_Constant(UncheckedBaseModel):
    source: typing.Literal["constant"] = "constant"
    constant_value: typing.Optional[ConstantSchemaOverrideConstantValue] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class ApiIntegrationWebhookOverridesSchemaOverridesValue_DynamicVariable(UncheckedBaseModel):
    source: typing.Literal["dynamic_variable"] = "dynamic_variable"
    dynamic_variable: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class ApiIntegrationWebhookOverridesSchemaOverridesValue_Llm(UncheckedBaseModel):
    source: typing.Literal["llm"] = "llm"
    prompt: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class ApiIntegrationWebhookOverridesSchemaOverridesValue_Omit(UncheckedBaseModel):
    source: typing.Literal["omit"] = "omit"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


ApiIntegrationWebhookOverridesSchemaOverridesValue = typing_extensions.Annotated[
    typing.Union[
        ApiIntegrationWebhookOverridesSchemaOverridesValue_Constant,
        ApiIntegrationWebhookOverridesSchemaOverridesValue_DynamicVariable,
        ApiIntegrationWebhookOverridesSchemaOverridesValue_Llm,
        ApiIntegrationWebhookOverridesSchemaOverridesValue_Omit,
    ],
    UnionMetadata(discriminant="source"),
]
