# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .audio_output_multi_alignment import AudioOutputMultiAlignment
from .audio_output_multi_normalized_alignment import AudioOutputMultiNormalizedAlignment


class AudioOutputMulti(UncheckedBaseModel):
    audio: str
    is_final: typing.Optional[bool] = None
    normalized_alignment: typing.Optional[AudioOutputMultiNormalizedAlignment] = None
    alignment: typing.Optional[AudioOutputMultiAlignment] = None
    context_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
