# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
from .batch_call_status import BatchCallStatus
import typing
from .outbound_call_recipient_response_model import OutboundCallRecipientResponseModel
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class BatchCallDetailedResponse(UncheckedBaseModel):
    """
    Detailed response model for a batch call including all recipients.
    """

    id: str
    phone_number_id: str
    name: str
    agent_id: str
    created_at_unix: int
    scheduled_time_unix: int
    total_calls_dispatched: int
    total_calls_scheduled: int
    last_updated_at_unix: int
    status: BatchCallStatus
    agent_name: str
    recipients: typing.List[OutboundCallRecipientResponseModel]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
