# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .auth_connection_dependencies import AuthConnectionDependencies
from .auth_connection_status import AuthConnectionStatus


class BearerAuthResponse(UncheckedBaseModel):
    """
    Response model for bearer auth
    """

    name: str
    provider: str
    id: str
    used_by: typing.Optional[AuthConnectionDependencies] = None
    status: typing.Optional[AuthConnectionStatus] = None
    status_detail: typing.Optional[str] = None
    status_updated_at: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
