# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .bytedance_seedream_5_lite_request_aspect_ratio import BytedanceSeedream5LiteRequestAspectRatio
from .bytedance_seedream_5_lite_request_resolution import BytedanceSeedream5LiteRequestResolution
from .image_reference import ImageReference
from .webhook_target import WebhookTarget


class BytedanceSeedream5LiteRequest(UncheckedBaseModel):
    """
    Request body for the ByteDance Seedream 5.0 Lite image model.
    """

    webhook: typing.Optional[WebhookTarget] = pydantic.Field(default=None)
    """
    Include to send the generation's result to the workspace's configured flows webhooks once it completes or fails. The webhook payload matches the terminal response of the corresponding GET endpoint.
    """

    prompt: str = pydantic.Field()
    """
    A text description of the image to generate.
    """

    images: typing.Optional[typing.List[ImageReference]] = pydantic.Field(default=None)
    """
    Up to 10 reference images to edit or draw from.
    """

    aspect_ratio: typing.Optional[BytedanceSeedream5LiteRequestAspectRatio] = pydantic.Field(default=None)
    """
    The aspect ratio of the output image. With `auto`, the model picks an aspect ratio based on the inputs.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    A seed for reproducible generation: the same seed and inputs give similar output across generations. Omit for random.
    """

    resolution: typing.Optional[BytedanceSeedream5LiteRequestResolution] = pydantic.Field(default=None)
    """
    The resolution of the output image.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
