# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .chapter_content_block_response_model import ChapterContentBlockResponseModel


class ChapterContentResponseModel(UncheckedBaseModel):
    blocks: typing.List[ChapterContentBlockResponseModel]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
