# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel


class ConversationSource(UncheckedBaseModel):
    type: typing.Optional[typing.Literal["conversation"]] = None
    conversation_id: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
