# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel


class ConversationAsrUsageModel(UncheckedBaseModel):
    """
    Aggregated ASR usage for a conversation (analytics-only, not billing).
    """

    asr_model: typing.Optional[str] = None
    total_transcription_calls: typing.Optional[int] = None
    total_audio_input_seconds: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
