# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel


class CreateClientParams(UncheckedBaseModel):
    """
    Create a new client in the system.
    """

    smb_tool_type: typing.Optional[typing.Literal["create_client"]] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
