# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DialogueTextAlignment(UncheckedBaseModel):
    """
    Character-level alignment data (field names use snake_case in JSON).
    """

    chars: typing.Optional[typing.List[str]] = None
    char_start_times_ms: typing.Optional[typing.List[int]] = None
    char_durations_ms: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
