# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .dubbing_target_transcript_segment import DubbingTargetTranscriptSegment


class DubbingBulkTargetSegmentUpdateResponse(UncheckedBaseModel):
    """
    The result of a bulk target edit: the updated segments and the new revision.
    """

    segments: typing.List[DubbingTargetTranscriptSegment] = pydantic.Field()
    """
    The edited target segments in their updated state.
    """

    revision: int = pydantic.Field()
    """
    The target's revision after the edits.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
