# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .get_knowledge_base_dependent_agents_response_model_agents_item import (
    GetKnowledgeBaseDependentAgentsResponseModelAgentsItem,
)


class GetKnowledgeBaseDependentAgentsResponseModel(UncheckedBaseModel):
    agents: typing.List[GetKnowledgeBaseDependentAgentsResponseModelAgentsItem]
    next_cursor: typing.Optional[str] = None
    has_more: bool

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
