# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .moderation_guardrail_input import ModerationGuardrailInput


class GuardrailsV1Input(UncheckedBaseModel):
    version: typing.Optional[typing.Literal["1"]] = None
    moderation: typing.Optional[ModerationGuardrailInput] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
