# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .initialise_context_generation_config import InitialiseContextGenerationConfig
from .initialise_context_pronunciation_dictionary_locators_item import (
    InitialiseContextPronunciationDictionaryLocatorsItem,
)
from .initialise_context_voice_settings import InitialiseContextVoiceSettings


class InitialiseContext(UncheckedBaseModel):
    text: str
    voice_settings: typing.Optional[InitialiseContextVoiceSettings] = None
    generation_config: typing.Optional[InitialiseContextGenerationConfig] = None
    pronunciation_dictionary_locators: typing.Optional[
        typing.List[InitialiseContextPronunciationDictionaryLocatorsItem]
    ] = None
    xi_api_key: typing.Optional[str] = None
    authorization: typing.Optional[str] = None
    context_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
