# This file was auto-generated by Fern from our API Definition.

import typing

MediaGenerationFailedResponseFailureReason = typing.Union[
    typing.Literal[
        "timeout",
        "model_error",
        "moderated",
        "invalid_parameters",
        "dependency_failed",
        "charging_failed",
        "internal_error",
    ],
    typing.Any,
]
