# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .detailed_music_response import DetailedMusicResponse


class MultipartMusicResponse(UncheckedBaseModel):
    """
    Multipart response structure with JSON metadata and binary audio
    """

    metadata: DetailedMusicResponse = pydantic.Field()
    """
    JSON metadata about the generated audio
    """

    audio: bytes = pydantic.Field()
    """
    Binary audio data in the requested format
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
