# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import update_forward_refs
from ..core.unchecked_base_model import UncheckedBaseModel
from .object_json_schema_property_input_property_kind import ObjectJsonSchemaPropertyInputPropertyKind
from .required_constraints import RequiredConstraints


class ObjectJsonSchemaPropertyInput(UncheckedBaseModel):
    property_kind: typing.Optional[ObjectJsonSchemaPropertyInputPropertyKind] = None
    description: typing.Optional[str] = None
    dynamic_variable: typing.Optional[str] = pydantic.Field(default=None)
    """
    When set, the entire parameter is populated from this dynamic variable at runtime. Mutually exclusive with description (LLM-provided value), constant_value, and is_omitted.
    """

    constant_value: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    When set, the entire object uses this constant JSON value at runtime. Mutually exclusive with description (LLM-provided object), dynamic_variable, and is_omitted.
    """

    is_omitted: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, this parameter will be completely omitted from the request. Only valid for optional parameters. Mutually exclusive with description, dynamic_variable, and constant_value.
    """

    type: typing.Optional[typing.Literal["object"]] = None
    required: typing.Optional[typing.List[str]] = None
    properties: typing.Optional[typing.Dict[str, "ObjectJsonSchemaPropertyInputPropertiesValue"]] = None
    required_constraints: typing.Optional[RequiredConstraints] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


from .array_json_schema_property_input import ArrayJsonSchemaPropertyInput  # noqa: E402, I001
from .array_json_schema_property_input_items import ArrayJsonSchemaPropertyInputItems  # noqa: E402, I001
from .object_json_schema_property_input_properties_value import ObjectJsonSchemaPropertyInputPropertiesValue  # noqa: E402, I001

update_forward_refs(
    ObjectJsonSchemaPropertyInput,
    ArrayJsonSchemaPropertyInput=ArrayJsonSchemaPropertyInput,
    ArrayJsonSchemaPropertyInputItems=ArrayJsonSchemaPropertyInputItems,
    ObjectJsonSchemaPropertyInputPropertiesValue=ObjectJsonSchemaPropertyInputPropertiesValue,
)
