# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .eagerness import Eagerness
from .turn_detection_type import TurnDetectionType


class OpenAiTurnDetection(UncheckedBaseModel):
    type: typing.Optional[TurnDetectionType] = None
    eagerness: typing.Optional[Eagerness] = None
    create_response: typing.Optional[bool] = None
    interrupt_response: typing.Optional[bool] = None
    threshold: typing.Optional[float] = None
    prefix_padding_ms: typing.Optional[int] = None
    silence_duration_ms: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
