# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .required_constraint import RequiredConstraint


class RequiredConstraints(UncheckedBaseModel):
    """
    Wrapper for anyOf/allOf composition constraints scoped to required fields.
    """

    any_of: typing.Optional[typing.List[RequiredConstraint]] = None
    all_of: typing.Optional[typing.List[RequiredConstraint]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
