# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ScheduleGroupSessionParams(UncheckedBaseModel):
    """
    Schedule a single instance of a group service.

    The session's duration is derived from the parent service so the assistant
    only has to pin start time, the (optional) instructor / room, and the
    location. Participants register separately via
    ``register_for_group_session``.
    """

    smb_tool_type: typing.Optional[typing.Literal["schedule_group_session"]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
