# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel


class ScribeChunkSizeExceededError(UncheckedBaseModel):
    message_type: typing.Literal["chunk_size_exceeded"] = "chunk_size_exceeded"
    error: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
