# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .similar_voice_category import SimilarVoiceCategory


class SimilarVoice(UncheckedBaseModel):
    voice_id: str
    name: str
    category: SimilarVoiceCategory
    description: typing.Optional[str] = None
    preview_url: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
