# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
from .similar_voice_category import SimilarVoiceCategory
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class SimilarVoice(UncheckedBaseModel):
    voice_id: str
    name: str
    category: SimilarVoiceCategory
    description: typing.Optional[str] = None
    preview_url: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
