# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class StoredUsagePlatformLimit(UncheckedBaseModel):
    """
    Platform limit with usage stored in Firestore. Example: credit usage tracked in Firestore.
    """

    limit: typing.Optional[int] = None
    usage: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current usage
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
