# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .template_array_output_failure_reason import TemplateArrayOutputFailureReason
from .template_audio_output_failure_reason import TemplateAudioOutputFailureReason
from .template_boolean_output_failure_reason import TemplateBooleanOutputFailureReason
from .template_image_output_failure_reason import TemplateImageOutputFailureReason
from .template_integer_output_failure_reason import TemplateIntegerOutputFailureReason
from .template_number_output_failure_reason import TemplateNumberOutputFailureReason
from .template_object_output_failure_reason import TemplateObjectOutputFailureReason
from .template_run_status import TemplateRunStatus
from .template_string_output_failure_reason import TemplateStringOutputFailureReason
from .template_video_output_failure_reason import TemplateVideoOutputFailureReason


class TemplateOutput_Array(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["array"] = "array"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateArrayOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content: typing.Optional[typing.List["TemplateOutput"]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_Audio(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["audio"] = "audio"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateAudioOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content_url: typing.Optional[str] = None
    content_mime_type: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_Boolean(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["boolean"] = "boolean"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateBooleanOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_Image(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["image"] = "image"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateImageOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content_url: typing.Optional[str] = None
    content_mime_type: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_Integer(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["integer"] = "integer"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateIntegerOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_Number(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["number"] = "number"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateNumberOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_Object(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["object"] = "object"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateObjectOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content: typing.Optional[typing.Dict[str, typing.Optional["TemplateOutput"]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_String(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["string"] = "string"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateStringOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TemplateOutput_Video(UncheckedBaseModel):
    """
    One output of a template run, discriminated on `type`: the `type` of the
    port's `content_schema`. Check `status` for where it is in its lifecycle.
    """

    type: typing.Literal["video"] = "video"
    id: str
    status: TemplateRunStatus
    failure_reason: typing.Optional[TemplateVideoOutputFailureReason] = None
    error_message: typing.Optional[str] = None
    content_url: typing.Optional[str] = None
    content_mime_type: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


TemplateOutput = typing_extensions.Annotated[
    typing.Union[
        TemplateOutput_Array,
        TemplateOutput_Audio,
        TemplateOutput_Boolean,
        TemplateOutput_Image,
        TemplateOutput_Integer,
        TemplateOutput_Number,
        TemplateOutput_Object,
        TemplateOutput_String,
        TemplateOutput_Video,
    ],
    UnionMetadata(discriminant="type"),
]
from .template_object_output import TemplateObjectOutput  # noqa: E402, I001
from .template_array_output import TemplateArrayOutput  # noqa: E402, I001

update_forward_refs(TemplateOutput_Array, TemplateObjectOutput=TemplateObjectOutput, TemplateOutput=TemplateOutput)
update_forward_refs(TemplateOutput_Object, TemplateArrayOutput=TemplateArrayOutput, TemplateOutput=TemplateOutput)
