# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .agent_transfer_input import AgentTransferInput


class TransferToAgentToolConfigInput(UncheckedBaseModel):
    transfers: typing.List[AgentTransferInput]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
