# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .image_reference import ImageReference
from .veo_image_reference_role import VeoImageReferenceRole


class VeoImageReference(UncheckedBaseModel):
    """
    A reference image guiding a Veo generation, with its role.
    """

    image: ImageReference = pydantic.Field()
    """
    The reference image.
    """

    role: VeoImageReferenceRole = pydantic.Field()
    """
    How the model uses the image: `subject` places its subject or scene elements into the video; `style` transfers its visual style.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
